#!/usr/bin/env python3
"""Regenerate the homepage "Latest News" teaser from news.qmd.

Runs as a Quarto project pre-render script (see _quarto.yml). News lives
entirely in news.qmd (one file, newest entry first). This script pulls the
first three entries out of it and writes _includes/recent-news.qmd, which
index.qmd includes.

Edit news.qmd, not the generated file -- it is overwritten on every render.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NEWS_PATH = ROOT / "news.qmd"
OUT_PATH = ROOT / "_includes" / "recent-news.qmd"
MAX_ITEMS = 3

GENERATED_HEADER = (
    "<!--\n"
    "  AUTO-GENERATED by _build/generate_news.py from news.qmd.\n"
    "  Do not edit this file by hand -- edit news.qmd instead.\n"
    "-->\n"
)

ENTRY_RE = re.compile(r"^## (.+?)\n\*(.+?)\*", re.MULTILINE)


def main():
    text = NEWS_PATH.read_text()
    entries = ENTRY_RE.findall(text)[:MAX_ITEMS]

    if not entries:
        body = "<p><em>None yet.</em></p>\n"
    else:
        rows = "\n".join(
            f'<tr><td>{date}</td><td><a href="news.qmd">{title}</a></td></tr>'
            for title, date in entries
        )
        body = (
            '<div class="projects-table-wrap">\n'
            '<table class="projects-table">\n'
            "<tbody>\n"
            f"{rows}\n"
            "</tbody>\n"
            "</table>\n"
            "</div>\n"
        )

    OUT_PATH.write_text(GENERATED_HEADER + "\n" + body)
    print(f"wrote {OUT_PATH.relative_to(ROOT)} ({len(entries)} entries)")


if __name__ == "__main__":
    main()
