#!/usr/bin/env python3
"""Regenerate the publication-list includes from papers.bib.

Runs as a Quarto project pre-render script (see _quarto.yml). Reads
papers.bib and writes:
  _includes/recent-publications.qmd        (entries with recent = {true})
  _includes/pub-journal-articles.qmd       (@article)
  _includes/pub-conference-proceedings.qmd (@inproceedings / @conference)
  _includes/pub-preprints.qmd              (@preprint)
  _includes/pub-patents.qmd                (@patent)
  _includes/pub-thesis.qmd                 (@phdthesis / @mastersthesis)
  _includes/pub-reports.qmd                (@techreport / @misc / @unpublished)

Edit papers.bib, not the generated files -- they are overwritten on every
render.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIB_PATH = ROOT / "papers.bib"
INCLUDES_DIR = ROOT / "_includes"

# Author name, exactly as it appears in papers.bib author fields, to bold
# as the site owner within author lists.
SELF_NAME = "Ahmed, Usman"

GENERATED_HEADER = (
    "<!--\n"
    "  AUTO-GENERATED by _build/generate_publications.py from papers.bib.\n"
    "  Do not edit this file by hand -- edit papers.bib instead.\n"
    "-->\n"
)


def parse_bib(text):
    entries = []
    entry_re = re.compile(r"@(\w+)\s*\{\s*([^,\s]+)\s*,")
    for m in entry_re.finditer(text):
        etype = m.group(1).lower()
        key = m.group(2)
        start_brace = text.index("{", m.start())
        depth, j, n = 0, start_brace, len(text)
        while j < n:
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        body = text[m.end():j]
        fields = parse_fields(body)
        fields.update(type=etype, key=key)
        entries.append(fields)
    return entries


def parse_fields(body):
    fields = {}
    i, n = 0, len(body)
    while i < n:
        while i < n and body[i] in " \t\r\n,":
            i += 1
        if i >= n:
            break
        m = re.match(r"[A-Za-z_][A-Za-z0-9_]*", body[i:])
        if not m:
            break
        name = m.group(0).lower()
        i += m.end()
        while i < n and body[i] in " \t\r\n":
            i += 1
        if i >= n or body[i] != "=":
            break
        i += 1
        while i < n and body[i] in " \t\r\n":
            i += 1
        if i >= n:
            break
        if body[i] == "{":
            depth, start = 0, i
            while i < n:
                if body[i] == "{":
                    depth += 1
                elif body[i] == "}":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            value = body[start + 1:i - 1]
        elif body[i] == '"':
            i += 1
            start = i
            while i < n and body[i] != '"':
                i += 1
            value = body[start:i]
            i += 1
        else:
            start = i
            while i < n and body[i] not in ",\n":
                i += 1
            value = body[start:i].strip()
        fields[name] = " ".join(value.split()).replace(r"\&", "&")
        i += 1
    return fields


def format_authors(author_field):
    names = [a.strip() for a in author_field.split(" and ") if a.strip()]
    formatted = []
    for name in names:
        html = f'<span class="pub-self">{name}</span>' if name == SELF_NAME else name
        formatted.append(html)
    if len(formatted) == 1:
        return formatted[0]
    if len(formatted) == 2:
        return f"{formatted[0]} & {formatted[1]}"
    return ", ".join(formatted[:-1]) + f", & {formatted[-1]}"


def format_body(entry):
    etype = entry["type"]
    year = entry.get("year", "n.d.")
    authors = format_authors(entry.get("author", ""))
    title = entry.get("title", "")

    if etype == "article":
        parts = [f"*{entry['journal']}*"] if "journal" in entry else []
        if "volume" in entry:
            parts.append(entry["volume"])
        if "pages" in entry:
            parts.append(entry["pages"])
        venue = ", ".join(parts)
        result = f"{authors} ({year}). {title}. {venue}."

    elif etype in ("inproceedings", "conference"):
        parts = [f"*{entry['booktitle']}*"] if "booktitle" in entry else []
        if "address" in entry:
            parts.append(entry["address"])
        venue = ", ".join(parts)
        result = f"{authors} ({year}). {title}. {venue}."

    elif etype == "techreport":
        preparedfor = entry.get("preparedfor")
        tail = f" Prepared for {preparedfor}." if preparedfor else ""
        result = f'{authors} ({year}). *{title}.*{tail}'

    elif etype in ("phdthesis", "mastersthesis"):
        label = "Doctoral dissertation" if etype == "phdthesis" else "Master's thesis"
        school = entry.get("school", "")
        result = f'{authors} ({year}). *{label}: "{title}."* {school}.'

    elif etype == "patent":
        note = entry.get("note", "")
        tail = f" {note}." if note else ""
        result = f'{authors} ({year}). *{title}.*{tail}'

    elif etype == "preprint":
        note = entry.get("note", "")
        tail = f" {note}." if note else ""
        result = f'{authors} ({year}). {title}.{tail}'

    else:
        # Fallback for any other/misc type.
        result = f"{authors} ({year}). {title}."

    # Collapse accidental double periods (e.g. an author initial or an
    # abbreviated venue like "D.C." landing right before a sentence-ending
    # period).
    return re.sub(r"\.{2,}", ".", result)


LINK_LABELS = [
    ("pdf", "PDF"),
    ("doi", "DOI"),
    ("free", "Free Download"),
    ("data", "Data"),
    ("code", "Code"),
    ("slides", "Slides"),
]


def format_links(entry):
    links = []
    for field, label in LINK_LABELS:
        value = entry.get(field)
        if not value:
            continue
        url = f"https://doi.org/{value}" if field == "doi" and not value.startswith("http") else value
        links.append(f"[{label}]({url})")
    return " ".join(links)


def render_entry(entry):
    body = format_body(entry)
    links = format_links(entry)
    links_html = f'\n<div class="pub-links">{links}</div>' if links else ""
    year = entry.get("year", "n.d.")
    return (
        "::: {.pub-entry}\n"
        f'<span class="pub-year">{year}</span>\n'
        "<div class=\"pub-body\">\n"
        f"<p>{body}</p>{links_html}\n"
        "</div>\n"
        ":::"
    )


def render_list(entries):
    body = "\n\n".join(render_entry(e) for e in entries)
    return f"::: {{.pub-list}}\n{body}\n:::\n"


def sort_key(entry):
    try:
        year = int(entry.get("year", 0))
    except ValueError:
        year = 0
    return -year


def write_include(filename, entries):
    path = INCLUDES_DIR / filename
    if not entries:
        content = GENERATED_HEADER + "\n<p><em>None yet.</em></p>\n"
    else:
        content = GENERATED_HEADER + "\n" + render_list(sorted(entries, key=sort_key))
    path.write_text(content)
    print(f"wrote {path.relative_to(ROOT)} ({len(entries)} entries)")


def main():
    text = BIB_PATH.read_text()
    entries = parse_bib(text)

    recent = [e for e in entries if e.get("recent", "").lower() == "true"]
    journal = [e for e in entries if e["type"] == "article"]
    conference = [e for e in entries if e["type"] in ("inproceedings", "conference")]
    preprints = [e for e in entries if e["type"] == "preprint"]
    patents = [e for e in entries if e["type"] == "patent"]
    thesis = [e for e in entries if e["type"] in ("phdthesis", "mastersthesis")]
    reports = [e for e in entries if e["type"] in ("techreport", "misc", "unpublished")]

    INCLUDES_DIR.mkdir(exist_ok=True)
    write_include("recent-publications.qmd", recent)
    write_include("pub-journal-articles.qmd", journal)
    write_include("pub-conference-proceedings.qmd", conference)
    write_include("pub-preprints.qmd", preprints)
    write_include("pub-patents.qmd", patents)
    write_include("pub-thesis.qmd", thesis)
    write_include("pub-reports.qmd", reports)


if __name__ == "__main__":
    main()
